name: Python - publish
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  build:
    name: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev
        working-directory: sec-gemini-python
      - name: Build
        run: uv build
        working-directory: sec-gemini-python
      - name: Publish
        run: uv publish -t ${{ secrets.PYPI_TOKEN }}
        working-directory: sec-gemini-python