name: Python - Run checks and tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "42 */6 * * *"
        
permissions:
  contents: read
  id-token: write
jobs:
  build:
    name: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev
        working-directory: sec-gemini-python

      - name: Check source
        run: bash ./scripts/check_source.sh
        working-directory: sec-gemini-python
        
      - name: Run tests
        run: uv run -m pytest
        working-directory: sec-gemini-python
        env:
          SEC_GEMINI_API_KEY: ${{ secrets.SEC_GEMINI_API_KEY }}
