name: WebComponent - publish
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # pin@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Build
        working-directory: web-component
        run: |
          npm ci
          npm run build
      - name: Publish
        working-directory: web-component
        run: npm publish # --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
